default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  username: <%= ENV.fetch("DB_USERNAME") { "my_blog" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>

development:
  <<: *default
  database: my_blog_development

test:
  <<: *default
  database: my_blog_test

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("DB_NAME") { "my_blog_production" } %>
  cache:
    <<: *default
    database: <%= ENV.fetch("DB_NAME") { "my_blog_production" } %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: <%= ENV.fetch("DB_NAME") { "my_blog_production" } %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= ENV.fetch("DB_NAME") { "my_blog_production" } %>
    migrations_paths: db/cable_migrate
